---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-config--example
  annotations:
    {{- include "app.annotations" . | indent 4 }}
  labels:
    {{- include "app.labels" . | indent 4 }}
type: Opaque
stringData:
  TAILSCALE_AUTH_KEY: {{ "THIS-IS-A-SAMPLE. Please create a real one independently" |b64enc }}
