---
on:
  pull_request:
  push:

jobs:
  helm-v3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: install

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run helm-docs
        run: .github/helm-docs.sh

  kubeval:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # When changing versions here, check that the version exists at: https://github.com/instrumenta/kubernetes-json-schema
        k8s:
          - v1.21.11
          - v1.22.8
          - v1.23.5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Add dependency chart repos
      #   run: |
      #     helm repo add stable https://charts.helm.sh/stable

      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh
